# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'juns_feeder_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for juns_feeder_app

  target 'juns_feeder_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'juns_feeder_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'

end
